### ISSUE TITLE
 only returns 720p 

### ISSUE THREAD

**Issue by 3052** [lpuglia/ExtTv#1]
https://www.raiplay.it/programmi/thenorthman

**Comment by lpuglia** [comment]
do you mind any extra explanation

**Comment by 3052** [comment]
MPD height returned is only 720p with the above URL

**Comment by lpuglia** [comment]
how is this related to the codebase? that stream is not available in the default plugins

**Comment by 3052** [comment]
what stream?

**Comment by lpuglia** [comment]
this is the codebase for an android tv app, not sure how to help you

**Comment by 3052** [comment]
can you check the URL above with the codebase and see what quality is returned?

**Comment by lpuglia** [comment]
no, the codebase doesn't support that url by default, you will have to tell me how you are doing so

**Comment by 3052** [comment]
what about this https://github.com/lpuglia/ExtTv/blob/master/plugins/raiplugin.js

**Comment by lpuglia** [comment]
what about this what?

**Comment by 3052** [comment]
it appears https://www.raiplay.it/ is supported according to  https://github.com/lpuglia/ExtTv/blob/master/plugins/raiplugin.js - so https://www.raiplay.it/programmi/thenorthman should be supported
